
*** Unable to find 'version' in setup.py of ui
Traceback (most recent call last):
  File "/opt/ros/noetic/share/catkin/cmake/interrogate_setup_dot_py.py", line 255, in <module>
    main()
  File "/opt/ros/noetic/share/catkin/cmake/interrogate_setup_dot_py.py", line 248, in main
    runpy.run_path(args.setupfile_path)
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/work/projects/intelijet_v2/intelijet_v2_ws/src/ui/setup.py", line 3, in <module>
    setup(
  File "/opt/ros/noetic/share/catkin/cmake/interrogate_setup_dot_py.py", line 181, in setup
    raise RuntimeError('version not found in setup.py')
RuntimeError: version not found in setup.py
[31m[1mCMake Error[0m at /opt/ros/noetic/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/mnt/c/work/projects/intelijet_v2/intelijet_v2_ws/build/ui/catkin_generated/env_cached.sh
  "/usr/bin/python3"
  "/opt/ros/noetic/share/catkin/cmake/interrogate_setup_dot_py.py" "ui"
  "/mnt/c/work/projects/intelijet_v2/intelijet_v2_ws/src/ui/setup.py"
  "/mnt/c/work/projects/intelijet_v2/intelijet_v2_ws/build/ui/catkin_generated/setup_py_interrogation.cmake")
  returned error code 1
[36mCall Stack (most recent call first):[0m
  /opt/ros/noetic/share/catkin/cmake/catkin_python_setup.cmake:46 (safe_execute_process)
  CMakeLists.txt:24 (catkin_python_setup)


make: *** [Makefile:390: cmake_check_build_system] Error 1
